// <auto-generated />
using InventoryService.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace InventoryService.Infrastructure.Migrations
{
    [DbContext(typeof(InventoryDbContext))]
    partial class InventoryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("InventoryService.Domain.Entities.InventoryItem", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProductId")
                        .IsUnique();

                    b.ToTable("InventoryItems");

                    b.HasData(
                        new
                        {
                            Id = "01JGNX5AA0QQNVENZZRY000001",
                            ProductId = "01JGNX4SP0QZVS6QF4R3ZCWGA1",
                            Quantity = 50
                        },
                        new
                        {
                            Id = "01JGNX5AA0QQNVENZZRY000002",
                            ProductId = "01JGNX4SP0QZVS6QF4R3ZCWGA2",
                            Quantity = 100
                        },
                        new
                        {
                            Id = "01JGNX5AA0QQNVENZZRY000003",
                            ProductId = "01JGNX4SP0QZVS6QF4R3ZCWGA3",
                            Quantity = 200
                        },
                        new
                        {
                            Id = "01JGNX5AA0QQNVENZZRY000004",
                            ProductId = "01JGNX4SP0QZVS6QF4R3ZCWGA4",
                            Quantity = 150
                        },
                        new
                        {
                            Id = "01JGNX5AA0QQNVENZZRY000005",
                            ProductId = "01JGNX4SP0QZVS6QF4R3ZCWGA5",
                            Quantity = 30
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
